project:
  type: book
  output-dir: docs
  resources:
    - google4a285867c35ac84f.html
    - BingSiteAuth.xml

book:
  site-url: https://paithiov909.github.io/shotcut-shiryo
  title: "Shotcut 資料"
  description: |
    Shotcutの基本的な使い方を紹介します
  image: assets/video-editing.png
  favicon: favicon.ico
  open-graph:
    locale: ja
  twitter-card:
    card-style: summary
  chapters:
    - index.qmd
    - intro.qmd
    - todo.qmd
    - transition.qmd
    - filter-video.qmd
    - filter-audio.qmd
    - keyframe.qmd
    - color-grading.qmd

format:
  html:
    theme: cosmo
    css: [style.css]
    mainfont: |
      -apple-system, "BlinkMacSystemFont", "Helvetica Neue", Helvetica, "Arial", "ヒラギノ角ゴ ProN W3", "Hiragino Kaku Gothic ProN", "メイリオ", Meiryo, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"
  docx:
    toc: false
    number-sections: true
filters:
  - collapse-social-embeds
