# Subtitle Editで字幕をつける

> 🚧準備中🚧

## Subtitle Editで文字入れする理由

### さまざまな「字幕」とその役割

日本語で「字幕」や「テロップ」などと呼ばれるものは、それらの文字を動画に入れる目的に注目することで、いくつかの種類に分けることができます。

たとえば、「テロップ」といった場合、発話の一部にあわせて表示することで、その発話内容を強調するような役割をする文字を指すことがあります。一方で、「字幕（captions）」といった場合、発話内容のほかに、それらの話者や、そのシーンで鳴っている効果音なども含めて文字に起こすことで、音声から情報を得ることが困難な人でも動画の内容を把握できるよう助ける役割をする文字を指したりします。ほかにも、その音声を母語としない人向けに、発話内容の翻訳を提供するような「字幕（subtitles）」というのもあります。

### Shotcutでの文字入れは不便

Shotcutだけでこういった文字入れをおこないたい場合、この資料で紹介した「テキスト：シンプル」や「テキスト：リッチテキスト」といったフィルタを利用することができます。また、Shotcutのフィルタとして文字入れせずに、個々の「テロップ」を画像などとして用意して、それらをクリップとして配置していけば、もっとさまざまな工夫を凝らしたデザインの文字を入れることができるでしょう。

しかし、いずれにせよ、Shotcutで発話にあわせた内容の文字入れをしようとすると、原則として、表示させる内容の数だけクリップを用意することにならざるをえません。表示させる内容が少なければそれでも構わないのですが、動画を通じて文字入れしなければならない箇所が増えてくると、こうした方法はいくつかの点で不便なものになりがちです。

まず、表示させる内容をそれぞれ異なるクリップとして扱おうとするのでは、はじめにそれらのクリップを用意するのにかなり時間がかかります。また、そうしたやり方では、それぞれの文字を適当なタイミングに割り付ける作業が大変ですし、後から内容やデザインを調整したいというときにも手間がかかってしまいます。

### 字幕ファイルとSubtitle Edit

そこで、とりわけ、動画の要所でちょっとした「テロップ」を表示させたいというのではなく、発話内容のほとんどすべてを文字起こしした「字幕」をつけたいという場合では、そうした文字は字幕ファイルとして扱うと便利です。

字幕ファイルというのは、動画を再生したときに表示させたい「字幕」の内容を書くためのテキストファイルです。たとえば、次のテキストは、WebVTTという形式の字幕ファイルの一部です。

```
WEBVTT

00:00:19.518 --> 00:00:23.891
早速ですが　みなさんは
この記号を見たことがありますか？

00:00:24.172 --> 00:00:29.389
この顔マークは
1980年代から1990年代ごろの

00:00:29.414 --> 00:00:32.928
漫画などで
よく使用されていた文字です

00:00:33.229 --> 00:00:37.715
このなんともシュールな表情が
印象に残りやすいことから

00:00:37.739 --> 00:00:41.372
現在でも覚えているという人も
多いかもしれません
```

字幕ファイルにはWebVTTのほかにも、SRTやASSといったいくつかの形式がありますが、いずれも基本的には、この例のように、ある動画ファイルの「字幕」として表示させたいテキストと、それらのテキストを表示させるタイミングとがまとめて記述されているものになります。

こうした字幕ファイルは、YouTubeの自動字幕などのように、動画の再生時に動画プレイヤーで重ねて表示させたりするほか、編集ソフトなどによってあらためて動画に書き出すことで映像の一部として埋め込んだりします。後者の方法は、字幕を動画に「焼き付ける」とか「焼き込む」などといわれる作業で、動画を再生する動画プレイヤーによらず「字幕」を表示させられる点で便利ですが、動画ファイルをあらためて書き出すことになるため、書き出しに時間がかかる点に注意が必要です。

:::{.callout-note}
たとえばDaVinci Resolveなど、動画編集ソフトのなかには、一部の形式の字幕ファイルを直接扱うことができるものがあります。

一方で、Shotcut（v24.06.26）では、今のところ、字幕ファイルを扱う機能は実装されていません。ただし、SRTファイルをインポートできるようにする機能が開発されているようなので、将来的には、Shotcutでもいちおう字幕ファイルを扱えるようになる可能性があります。
:::

このページでは、[Subtitle Edit](https://www.nikse.dk/subtitleedit)という字幕ファイル編集ソフトを取り上げ、動画に「字幕」をつける方法を紹介します。Subtitle Editは、その名前の通り、本来は翻訳を提供するような「字幕（subtitles）」をつける用途に特化したソフトウェアです。しかし、ここでは単に発話内容を文字起こしした程度の「字幕（captions）」をつけることを念頭に、動画ファイル用の字幕ファイルを作成したうえで、それを映像の一部として焼き込むやり方を説明します。

## Subtitle Editの使い方
