# フィルタ（音声）

## 音量を調整する

### 動画の音量について

ここでは、クリップの音量を小さくしたり、大きくしたりする方法について紹介します。一例として、次のような動画の音量を調整することを考えてみましょう。

:::{.youtube video_id=_SiQFBDLQbA title="元の音声ファイル" collapse=false}
:::

この動画では、同じ音声が3回繰り返されるように配置されています。ここで使われている音声ファイルは、レストランの店内の環境音をイメージしてあらかじめミックスされたものです。とくに近くの席にいると思われる女性が英語で何かを話す声や、赤ちゃんの声のほか、その他の人々が会話している声などが、喧騒のように鳴っていることがわかります。

:::{.callout-note}
このページに埋め込んでいるYouTube動画では、同じ音声をそれぞれ異なる音量で再生しているのですが、実際にYouTube動画として再生するかぎりでは、その違いを聞き取るのは難しいかもしれません。

というのも、YouTubeのプレイヤーにはユーザーが調整できるボリュームコントロールとは別に、動画の音量を自動的に調整する機能がそなわっています。そのため、ふつうに再生したときに音量が大きくなりすぎるだろう動画については自動で減音されてしまい、その動画の本来の音量では再生されません。

動画の本来の音量を確認するには、動画を再生中のYouTubeプレイヤーを右クリックすると表示されるメニューのなかから「詳細統計情報」をオンにしてください。表示される統計情報の「Volume / Normalized」の項目のNormalizedの値が自動減音機能のボリュームであるため、この値がより小さくなっている動画ほど、動画の本来の音量が大きいことの目安になります。
:::

この動画の音量を調整する前に、まず、ここでいう動画の音量とは何かを説明します。私たちが映像作品を再生するとき、映像作品の音量は、再生機器のボリュームを調整することによっても、自由に変更することができます。つまり、動画が実際にどれくらいの大きさの音で再生されるかは、その動画が再生される環境次第で変わってしまうものです。

そのため、Shotcutのような動画編集ソフトでは、動画の音量を「デジタル音声として正常に出力できる音の最大値を0としたときの相対値」によって表示します。このような音量の単位は「dBFS（デシベル・フルスケール）」と呼ばれるもので、この意味での動画の音量は、編集レイアウトでは画面の右上あたりに表示されている「音声ピークメーター」から確認することができます。

このdBFSの値が0よりも上に振り切れてしまうと、再生時に、いわゆる「音割れ」が発生するかもしれない状態になります。したがって、動画の音量を調整する際には、音声ピークメーターのピークが上端に振り切れない範囲で、適切だと思われる大きさに音量を調整することになります。

### ゲイン・音量

Shotcutで素材の音量を小さくしたり、大きくしたりするには、「ゲイン・音量」というフィルタを使うことができます。このフィルタでは「レベル」という値を設定することで、`-70.0dB`から`24.0dB`の範囲でクリップの音量を調整することができます。

ここで、「dB（デシベル）」というのは、「そのクリップの元の音量を0としたときの相対値」のような意味の単位です。`0.0dB`だと元の音量に対して等倍で、マイナス方向に振ると音量が小さくなり、プラス方向に振ると音量が大きくなります。

次の例は、上の動画について「ゲイン・音量」を適用して、`4.0dB`だけ音量を大きくしたものです。

:::{.youtube video_id=gUKAJ9VrBHU title="「ゲイン・音量」" collapse=false}
:::

### リミッター

先ほどの例では、「ゲイン・音量」を適用した結果、音声ピークメーターで確認するとピークが上端近くに振り切れてしまっているような箇所がありました。

「ゲイン・音量」は、元から大きな音も、小さな音も、それぞれ一律に設定したレベル分だけ小さくしたり、大きくしたりするため、元から大きな音では大きくなりすぎてしまったり、逆に元から小さな音では小さくなりすぎてしまったりする場合があります。

そこで、大きすぎる音の音量を抑制するには、「リミッター」というフィルタを使うことができます。Shotcutのリミッターでは「入力ゲイン」「リミット」「リリース」の3つの値を設定できますが、基本的には「リミット」として音量レベルの上限値を設定し、上限値を超えるような大きな音について音量を抑制するといった使い方をします。

次の動画は、先ほどの例について、「リミット」を`-3.0dB`として「リミッター」を適用した例です。

:::{.youtube video_id=F4w3xyyvHws title="「ゲイン・音量」＋「リミッター」" collapse=false}
:::

:::{.callout-tip}
Shotcutでは「リミッター」に「入力ゲイン」があるので、「ゲイン・音量」の後に「リミッター」を組み合わせるような使い方をする場合では、同じことを「リミッター」だけでも実現できます。
:::

### コンプレッサー

音量を全体的に大きくしつつも、大きくなりすぎる音については音量をある程度抑制するという処理には、結果として、音量を一定のレベルの範囲にならす（潰す）効果があります。

このように、大きな音に比べると小さな音であっても、必ずしも小さく聞こえるようにするわけではなく、音声全体がある程度の大きさを保って聞こえるように音量を調整することを指して、俗に「音圧を上げる」とか「音圧を稼ぐ」といった言い方をします。音声の自然な聞こえ方を保ちつつ音圧を上げるのは、慣れが必要でなかなか難しい作業なのですが、技術的には「コンプレッサー」のようなフィルタを利用することで実現できます。

Shotcutの「コンプレッサー」では、いくつかの値を設定できます。そのなかでも重要そうなものは「しきい値」「比率」「メイクアップゲイン」の3つです。

コンプレッサーは、メイクアップゲインで音量を調整しながら、しきい値を上回るような比較的大きな音について、比率で指定した割合になるように音量を下げるといったような処理をおこないます。結果的に、大きな音と小さな音とのあいだの音量の差が小さくなるので、適用したクリップの音量をならすことができます。

次の動画は、先ほどまでと同じクリップについて、「コンプレッサー」と「リミッター」を適用して音量を調整した例です。

:::{.youtube video_id=xUCRm5y5BDQ title="「コンプレッサー」＋「リミッター」" collapse=false}
:::

この例の意図として、ここでは、「ゲイン・音量」と「リミッター」を組み合わせた例よりも強く音量の差を潰したつもりです。背景で鳴っている会話の音量が先ほどの例よりも上がったように聞こえると思います。

<!--

## 特定の周波数帯の音量を下げる

> 🚧準備中🚧

私たち人間の耳には、聴覚特性と呼ばれるある種の「癖」があります。大雑把にいうと、同じ音量レベルで再生された音であっても、私たちの耳には、高い音ほど実際より大きな音のように聞こえ、低い音ほど実際より小さな音に聞こえるようになっています。

- ローパス・ハイパス・バンドパス
- ノッチ（刻み目）
- イコライザー（Equalizer）

-->
