# さまざまな動画の書き出し

## プリセットにない映像モードを追加する

Shotcutのデフォルトの映像モードのプリセットは、それほど充実してはいません。

Shotcutで既存のプリセットに存在しない解像度やfpsの組み合わせで動画をつくるには、「設定 > 映像モード > カスタム > 追加...」から、カスタム映像モードを追加します。カスタム映像モードは、作成時に「名前」を指定した場合にかぎり、[Shotcutのデータディレクトリ](https://www.shotcut.org/FAQ/#where-are-the-log-presets-cache-and-settings-stored)に保存されます。

「カスタム映像モードを追加」からは、次の項目を指定することができます。

1. 解像度（プルダウンからはHD～5Kまで選べる。手入力も可能）
2. アスペクト比（プルダウンからは`16:9`, `4:3`, `9:16`, `1:1`, `1.90:1`が選べる）
3. フレーム/秒（fps）
4. 走査方法（インターレースかプログレッシブのいずれか。ふつうはプログレッシブでよい）
5. 色空間（`BT.709`, `BT.601`, `BT.2020`のいずれか。ふつうは`BT.709`でよい）

### 解像度の早見表

次のページをもとに、一部の使いそうなものだけを表にまとめています。

- [モニタ解像度 図解チャート 一覧](https://www.quel.jp/etc/monitor-size/)
- [4:3、16:9などのサイズ一覧 - phantom4](https://blog.phantom4.org/archives/300)

#### アスペクト比 4:3

| | w | h |
| --- | --- | --- |
| QVGA | 320 | 240 |
| VGA | 640 | 480 |
| NTSC | 720 | 483 |
| PAL | 768 | 576 |
| SVGA | 800 | 600 |
| - | 960 | 720 |
| XGA | 1024 | 768 |
| XGA+ | 1152 | 864 |
| Quad-VGA | 1280 | 960 |
| SXGA+ | 1400 | 1050 |
| ハイビジョン | 1440 | 1080 |
| UXGA | 1600 | 1200 |
| QXGA | 2048 | 1536 |
| 4M | 2304 | 1728 |
| QUXGA | 3200 | 2400 |

#### アスペクト比 16:9

| | w | h |
| --- | --- | --- |
| HVGAW | 640 | 360 |
| FWVGA | 854 | 480 |
| QHD, QFH | 960 | 540 |
| WSVGA | 1024 | 576 |
| 720p | 1280 | 720 |
| FHD（1080i, 1080p） | 1920 | 1080 |
| QWXGA | 2048 | 1152 |
| WQHD | 2560 | 1440 |
| WQHD+ | 3200 | 1800 |
| 4K（2160i, 2160p）| 3840 | 2160 |

### fpsの早見表

| fps | numerator | denominator |
| --- | --- | --- |
| 23.98 | 24000 | 1001 |
| 24 | 24 | 1 |
| 25 | 25 | 1 |
| 29.97 | 30000 | 1001 |
| 30 | 30 | 1 |
| 50 | 50 | 1 |
| 59.94 | 60000 | 1001 |
| 60 | 60 | 1 |

## ffmpegのオプションを渡す

書き出し時にffmpegに渡されるべきオプションは、「書き出し > 詳細設定 > その他」のタブから指定することができます。ただし、詳細設定からオプションを追加する場合、ffmpeg側に不正なオプションの組み合わせが渡されてしまう可能性があるため、注意が必要です。

たとえば、「書き出し」中の組み込みプリセット「WebP Animation」から作成できるWebPアニメーションは、デフォルトのままだとループ再生しないものになりますが、「書き出し > 詳細設定 > その他」から`loop=0`を追加することで、無限ループするようにできます。

## タイムラインの一部だけを書き出す

Shotcutのマーカーは、Ctrlキーを押しながら端をドラッグすることで「区間」として設定することができます。

区間として設定されたマーカーは、書き出し時にタイムラインに代わる「出力元」として選択することができるため、マーカーを適当に設定することで、タイムラインの一部だけを動画ファイルとして書き出すことが可能です。
