# トランジション

## その他を開く

### 色

Shotcutでは、一部の特殊な形式の素材を扱うことができます（音声・映像デバイスからの入力など）。そうした特殊な素材を扱うには、画面の上部にある「[]{.shotcut-icon .document-new}（その他を開く...）」というメニューから、目的の形式を選択します。

「色」は、「[]{.shotcut-icon .document-new}（その他を開く...）」から作成できる素材の一つです。プロジェクトの解像度いっぱいのサイズの領域について、指定した単色で塗りつぶしただけの素材を作成することができます。色を指定しない場合、デフォルトでは無色透明（`#00000000`）な素材が作成されます。

:::{.callout-note}
ここでは、Shotcutの画面上での表示にならって、色コードを`#ff000000`のような形式で表示しています。先頭の2ケタはアルファチャンネル（A）で、残りはRGBの各チャンネルの値です。

Shotcutにおける色を選択する画面では、RGBAの各チャンネルを`0-255`の値の範囲で指定できるようになっています。`0-255`の範囲の値は16進数を使うと2ケタで表せることから、各チャンネルの値を16進数で表すことがよくおこなわれます。
:::

### テキスト

「テキスト」も「[]{.shotcut-icon .document-new}（その他を開く...）」から作成できる素材の一つです。こちらは、入力した内容が書かれたテキストボックス付きの「色」を作成することができます。

テキストボックスの内容や体裁を調整するには、トラックに配置した「テキスト」素材を選択した状態で、画面左上のパネルから「フィルタ」タブを開き、そのタブで「映像 > テキスト：シンプル（または、リッチテキスト）」を選択します。リッチテキストの場合は、プレビューのなかにあるテキストボックスを直接編集できるようになります。

:::{.callout-note}
「テキスト」から作成した素材は、実際には、指定した「色」に「テキスト：シンプル」または「テキスト：リッチテキスト」という「フィルタ」が適用されたクリップになります。

Shotcutにおける「フィルタ」機能については「[4  フィルタ（映像）](filter-video.html)」であらためて説明します。
:::

## クリップの長さを調整する

クリップの端にマウスカーソルをもっていくと、マウスカーソルのかたちが「↔」のようなかたちに変化します。その状態でクリップの端をつかんでドラッグすると、クリップを左右に伸縮させて、長さを調整することができます。

ただし、動画ファイルや音声ファイル、アニメーション付きのGIF画像ファイルなど、素材そのものが一定の尺をもっている場合では、素材ファイルの元の尺よりも長いクリップにすることはできません。なお、そうした素材そのものが一定の尺をもっているようなクリップについては、クリップを選択した状態で「プロパティ > 長さ」から長さを指定することで、ぴったり特定の長さに調整することができます。

また、画像ファイルなど、素材そのものが一定の尺をもたない場合では、クリップを左に伸ばすことはできません（素材そのものが一定の尺をもっている場合では、その素材の始まりまでであれば、左にも伸ばすことができます）。

:::{.callout-note}
Shotcutのような動画編集ソフトでは、プロジェクトの再生時間を「01:20:30:24」のような形式で表記します。これは、左から順に「時間:分:秒:フレーム番号」を表します。末尾の2ケタはフレーム番号（ただし、00から数えはじめます）なので、そのプロジェクトにおけるfpsの設定によって、1秒に繰り上がる数字が異なります。

たとえば、25fpsのプロジェクトの場合、「01:20:30:24」は「1時間20分30秒の24フレームめ」を表し、この一つ次のフレームは「01:20:31:00」になります。
:::

## トランジションをかける

映像作品において、カットが切り替わる際にかかる効果のことを「トランジション」と呼びます。たとえば、次の動画で使われているような効果のことです。

:::{.youtube video_id=Zs9uTZ3Y2dc title="トランジションの例" collapse=false}
:::

トランジションを上手く活用すると、カットの切り替わりに余韻をもたせたりすることができます。

:::{.callout-note}
もっとも、一般に、カットが切り替わるときに常に何らかのトランジションをかけなければいけないという話ではありません。たとえば、次のリンク先にある動画では、カットの切り替わりにトランジションは一切かかっていません。

[スズメ　公園の噴水で水浴び｜素材｜NHKアーカイブス](https://www2.nhk.or.jp/archives/movies/?id=D0002160954_00000)

むしろ、多くの映像作品において、ほとんどのカットの切り替わりはただ単にカットを繋げただけの映像になっています。トランジションは、ふつう、そうしてただ単にカットを繋げたのでは得られない効果が求められるときにだけ使います。

とくに狙いがないのにトランジションを多用してしまうと、かえって映像が素人っぽい仕上がりになりがちです。注意しましょう。
:::

Shotcutでクリップ間にトランジションを設定するには、まずはじめに、切り替え元のクリップと切り替え先のクリップとを一つのトラックに並べて配置します。それから、片方のクリップをドラッグして、もう一方のクリップと重なるようにすると、重なった部分が「トランジション」形式の新しいクリップになります。

トランジションは、それ自体が一つのクリップなので、通常のクリップと同様に、端をつかんでドラッグすることで長さを調整できます。また、トランジションを選択した状態で、「プロパティ > 映像」からトランジションの方法を変更できます。

試しに、トランジションを設定しているようすを見てみましょう。次の例では「[]{.shotcut-icon .document-new}（その他を開く...）」から、青（`#ff0000ff`）・白（`#fffafafa`）・オレンジ（`#ffff5500`）の背景の「テキスト」を作成し、この順番に一つのトラックに並べてから、トランジションを設定しています。

:::{.youtube video_id=lvmgdUV0ugo title="トランジションをかける" collapse=false}
:::

ここでは、各色の「テキスト」をそれぞれ2秒ずつ表示させ、それとは別に1秒ずつかけてトランジションするような動画をつくっています。つまり、各色のクリップの長さと重なり方は、次の図のようになっています。

```{mermaid}
gantt
  title クリップの長さと重なりのようす
  dateFormat  m:s
  axisFormat  %M:%S
  section 青
  ff0000ff（3秒） :blue, 0:0, 3s
  section 白
  fffafafa（4秒） :white, 0:2, 4s
  section オレンジ
  ffff5500（3秒） :orange, 0:5, 3s
```

## フェードインとフェードアウト

トランジションのほかに、フェードインやフェードアウトをかけることもできます。

フェードインというのは映像や音声をなめらかに表示・再生させる効果、フェードアウトはその反対になめらかに消す効果のことです。

Shotcutにおけるフェードインやフェードアウトは、フェードにかかる持続時間（長さ）が設定されたフィルタです。ただ、ほかのフィルタとは違って、フェードインとフェードアウトにかぎっては、クリップの上の隅をつかんで内側に向かってドラッグすることによって、直観的に適用することができます。

実際にフェードインやフェードアウトを適用しているようすを見てみましょう。

:::{.youtube video_id=Yki_GdQWLEY title="フェードイン・アウト" collapse=false}
:::

この例のように、映像のフェードインとフェードアウトは、フェードイン・アウトするクリップの下に別のトラックがある場合では、クリップの不透明率を変える挙動になります。つまり、そうした場合では、フェードイン・アウトを適用したクリップが透明な状態から徐々に表示されたり、逆に徐々に透明になったりします。

一方で、そのクリップの下に別のトラックがない場合には、黒い画面とのあいだでフェードイン・アウトします。この挙動は、フェードイン・アウトを適用したクリップを選択した状態で「フィルタ > 映像のフェードイン（または、フェードアウト） > 黒でフェードの代わりに不透明率を調整」というチェックボックスにチェックを入れることで変更することができます。

なお、黒以外の単色とのあいだでフェードしたい場合は、フェードイン・アウトするクリップの下のトラックに目的の「色」を配置したうえで、「黒でフェードの代わりに不透明率を調整」するようにすれば実現できます。
